#!/usr/bin/env bash

function main {
  local BUILD_DIR="$1"; shift
  local CACHE_DIR="$1"; shift
  local ENV_DIR="$1"; shift

  local ver_ruby="$(cat .ruby-version)"
  local fl_first_time=

  local pth_ruby_cache="${DATA}/cache/rbenv/${ver_ruby}-${GEM_VERSION}-${BUNDLER_VERSION}-${ID_INSTALL}.tgz"

  if [[ ! -d "${BOARD_PATH}/.rbenv.versions/${ver_ruby}" ]]; then
    if [[ ! -f "$pth_ruby_cache" ]]; then
      fl_first_time=1
    fi
  fi

  if [[ -f "$pth_ruby_cache" ]]; then
    (cd "${BOARD_PATH}" && tar xfz "$pth_ruby_cache")
  else
    rbenv install -s
    gem install bundler --conservative -v "${BUNDLER_VERSION}"
    gem update --system
  fi

  if [[ -n "$fl_first_time" ]]; then
    mkdir -p "${DATA}/cache/rbenv"
    (cd "${BOARD_PATH}" && tar cfz "$pth_ruby_cache" ".rbenv/versions/${ver_ruby}")
  fi
}

source sub "$0" "$@"
