#!/usr/bin/env bash

function main {
  local BUILD_DIR="$1"; shift
  local CACHE_DIR="$1"; shift
  local ENV_DIR="$1"; shift

  local ver_ruby="$(rbenv local)"
  local fl_first_time=

  local pth_ruby_cache="${DATA}/cache/rbenv/${ver_ruby}-${GEM_VERSION}-${BUNDLER_VERSION}-${ID_INSTALL}.tgz"

  set -x

  if [[ -f "$pth_ruby_cache" ]]; then
    (cd "${BOARD_PATH}" && gtar xfz "$pth_ruby_cache")
    rbenv rehash
  else
		case "${DISTRIB_UD}" in
			Ubuntu)
				${NOSUDO} sudo apt-get install ruby-bundler
				;;
		esac
    rbenv install -s
    mkdir -p "${DATA}/cache/rbenv"
    (cd "${BOARD_PATH}" && gtar cfz "$pth_ruby_cache" ".rbenv/versions/${ver_ruby}")
  fi

  rbenv rehash
  gem update --system="${GEM_VERSION}" || true
  rbenv rehash
  gem install -f bundler -v "${BUNDLER_VERSION}" || true
  rbenv rehash
}

source sub "$0" "$@"
