#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "${RUBY_BUILD_CACHE_PATH}"

  if [[ ! -d "$shome/.rbenv" ]]; then
    git clone git@github.com:rbenv/rbenv.git "$shome/.rbenv"
  fi

  if [[ ! -d "$shome/.ruby-build" ]]; then
    git clone git@github.com:rbenv/ruby-build.git "$shome/.ruby-build"
  fi
}

bootstrap
