#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile gitsubmodule

  cd "$shome/vendor/rbenv"
  git reset --hard "v$RUBY_ENV_VERSION"
  ln -nfs ../vendor/rbenv/bin/rbenv "$shome/bin/"

  cd "$shome/vendor/ruby-build"
  git reset --hard "v$RUBY_BUILD_VERSION"
  
  cd "$shome/bin"
  (set +f; ln -nfs ../vendor/ruby-build/bin/* "$shome/bin/")
}

main "$@"
