#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.rbenv')" != "$RUBY_ENV_VERSION" ]]; then
    return 1
  fi

  if [[ "$($shome/script/version | jq -r '.ruby_build')" != "$RUBY_BUILD_VERSION" ]]; then
    return 1
  fi

  if [[ ! -d "$(rbenv root)/plugins/rbenv-default-gems" ]]; then
    return 1
  fi

  return 0
}

main "$@"
