#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$($shome/script/version | jq -r '.rbenv')" != "$RUBY_ENV_VERSION" ]]; then
    return 1
  fi

  local sha="$(cd "$shome/vendor/ruby-build" && git rev-parse HEAD)"
  local nm_tags="$(cd "$shome/vendor/ruby-build" && git show-ref --tags | grep ^$sha | cut -d/ -f3- | xargs -- | sed 's# #,#g')"
  if [[ "$nm_tags" != "v$RUBY_BUILD_VERSION" ]]; then
    return 1
  fi

  if [[ ! -f "$(rbenv root)/plugins/rbenv-default-gems" ]]; then
    return 1
  fi

  return 0
}

main "$@"
