#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/.rbenv/bin:$shome/.ruby-build/bin:$PATH"

  export RUBY_BUILD_CACHE_PATH="${BASEBOX_CACHE}/cache/ruby"
}

profile
