#!/usr/bin/env bash

function _rbenv_profile {
  local shome="${_rbenv_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="${BOARD_PATH}/.rbenv/shims:$shome/bin:$shome/exec:$PATH"
  #export ANSIBLE_ROLES_PATH="$shome/roles${ANSIBLE_ROLES_PATH:+:${ANSIBLE_ROLES_PATH}}"
  #export ANSIBLE_LIBRARY="$shome/library${ANSIBLE_LIBRARY:+:${ANSIBLE_LIBRARY}}"

  RBENV_VERSION='1.1.1'
  RUBY_BUILD_VERSION='20170726'
}

_rbenv_profile
