#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_rbenv="$(rbenv 2>&1 | head -1 | awk '{print $2}' || true)"
  jq -n --arg rbenv "$ver_rbenv" '{rbenv: $rbenv}'
}

version "$@"
